### ISSUE TITLE
ModuleNotFoundError: No module named 'attrdict' when running

### ISSUE THREAD

**Issue by stringyao** [neptune-ml/kaggle-toxic-starter#10]

**Comment by stringyao** [comment]
Can't really train the model after the updating of Neptune.

**Comment by kamil-kaczmarek** [comment]
Hi @stringyao ,

It is really easy to fix - you just need to update `neptune-cli`. When in your virtualenv, use pip to run the update:
```bash
$ pip3 install neptune-cli -U
```

Let me know if it works.

Best,
Kamil
(@jakubczakon )

**Comment by jakubczakon** [comment]
Updated the requirements. It should work now.
