### ISSUE TITLE
Hard to reproduce results locally

### ISSUE THREAD

**Issue by lodurality** [neptune-ml/kaggle-toxic-starter#11]
Hi, I was able to run all models locally (run_end_to_end.sh) but weren't able to run catboost on top of the models. 

`TypeError: fit() missing 1 required positional argument: 'validation_data'`

It looks like I am missing something. Is it possible to reproduce your pipeline without loading data from the cloud?

**Comment by lodurality** [comment]
If it will help, here are some things that I noticed/changed:
-- wrong catboost config name parameter in run_end_to_end.sh (should config_catboost_ensemble.yaml instead of catboost_ensemble.yaml)
-- no mention of train_split.csv and valid_split.csv in local run instruction.
-- it's not hard but a bit annoying to rewrite paths in configs to your local paths. I would point them to local repo directory. 
-- same thing goes for ensembling notebook which points to data on the cluster. Also, names for particular models there (model_name.csv) differ from what run_end_toend.sh produces (model_name/submission.csv).

But overall it is very useful and interesting pipeline, which helped me a lot both in terms of ML and software design.

Thank you for sharing this!

**Comment by setuc** [comment]
@lodurality  how did you resolve the train_split.csv and valid_split.csv issue?

**Comment by jakubczakon** [comment]
@setuc Hi, you can generate train_split.csv and valid_split.csv by running 
neptune run experiment_manager.py --config neptune_config.yaml --train_valid_split 
on master or 
neptune run --train_valid_split on master

Just specify the paths in the neptune_config.yaml

@lodurality I am still working on this but everything seems to be working just fine on the dev branch.
I want to smoke test some stuff over the weekend and post a nice update on kaggle on Monday but if you are short on time just use the dev.

**Comment by jakubczakon** [comment]
@lodurality Fixes and improvements are on master now.
As for config management I am not sure if I want to employ something like ansible for every user or keep it simple as it is and let people put this layer of abstraction themselves if they want to. Some people will only have one neptune.yaml

**Comment by kamil-kaczmarek** [comment]
@jakubczakon @lodurality @setuc,

I'm closing this issue -> fixes are on `master`, and competition is over. Since last post here, a lot of improvements were added to our codebase.

Best,
KK
