### ISSUE TITLE
requirements.txt doesn't seem to work.

### ISSUE THREAD

**Issue by stringyao** [neptune-ml/kaggle-toxic-starter#17]
When I tried to run $ neptune send experiment_manager.py --environment keras-2.0-gpu-py3 --worker gcp-gpu-medium --config neptune_config.yaml -- train_evaluate_predict_pipeline --pipeline_name glove_lstm, the experiment failed because it failed to import attrdict.

However, this lib is already written in the requirements, and I guess somehow the program failed to check the requirements?

**Comment by jakubczakon** [comment]
If you look at your neptune_config.yaml file. 
Does it have the following line commented:

#Comment out if not in Cloud Environment
#pip-requirements-file: requirements.txt
 
if so, then uncomment pip-requirements-file: requirements.txt

**Comment by stringyao** [comment]
I'm able to fix the problem by reinstalling neptune-cli.
