### ISSUE TITLE
How to add parameter to select GPU at runtime?

### ISSUE THREAD

**Issue by setuc** [neptune-ml/kaggle-toxic-starter#23]
Hi,
 how do we add a command line parameter to the select the GPU at run time, especially on amulti gpu machine? 
I tried adding 

```python
@action.command()

@click.option('-g', '--gpu', help='select gpu', default=1, required=true)
def select_gpu(gpu):
    os.environ["CUDA_VISIBLE_DEVICES"]=gpu
```

I tried to add a similar code block for train_evaluate_predict_pipeline and pass the gpu parameter
but i keep getting invalid option during runtime. I know its not the package issue, but the [documentation](http://click.pocoo.org/6/) did not help either

**Comment by jakubczakon** [comment]
I usually do it just by going along these lines:

`CUDA_VISIBLE_DEVICES=1 neptune run -- train_evaluate_predict_pipeline -p fasttext_gru`

and for multigpu you just do:

`CUDA_VISIBLE_DEVICES=1,2 neptune run -- train_evaluate_predict_pipeline -p fasttext_gru`

I haven't tried multigpu for this project yet.

Also apart from the documentation we have quite a vibrant community here https://community.neptune.ml/
drop your issue there and I am sure someone will help.

**Comment by kamil-kaczmarek** [comment]
@setuc Also, you can do `$ export CUDA_VISIBLE_DEVICES=1`, to select particular GPU, for entire terminal session.
