### ISSUE TITLE
Vanished experiment_manager.py

### ISSUE THREAD

**Issue by laol777** [neptune-ml/kaggle-toxic-starter#24]
How can I run this code on the local machine? Accordance with your wiki, file `experiment_manager.py` exists in the repo and I should use it. But I don't see it. Could you help me?

https://github.com/neptune-ml/kaggle-toxic-starter/wiki/Experimentation-guideline

**Comment by jakubczakon** [comment]
I am sorry, we simplified it by changing `experiment_manager.py` to `main.py` .
You can either run it with main.py instaed of experiment_manager.py or simply omit this .py part (that is why main.py is better). 
I will fix the wiki in a moment.

**Comment by kamil-kaczmarek** [comment]
@laol777
Hey, thanks for pointing this out. As  @jakubczakon mentioned, we have renamed `experiment_manager.py` to `main.py`. Thanks to this, experiment execution command is simpler -> you do not need to specify Python file to execute. Command looks like this:
```bash
$ neptune send --environment keras-2.0-gpu-py3 --worker gcp-gpu-medium -- train_evaluate_predict_pipeline --pipeline_name glove_lstm
```
@laol777 please let us know if you will find more inaccuracies - we really appreciate this! ;-)

Best,

Kamil
