### ISSUE TITLE
Unable to access auth server. Login url is incorrect

### ISSUE THREAD

**Issue by rrdssfgcs** [neptune-ml/kaggle-toxic-starter#25]
When I run command "neptune login"
I got nothing but "Unable to access auth server. Login url is incorrect"
Is there anything wrong with the server?

**Comment by jakubczakon** [comment]
Hi, 
I will look into it right away. 
One thing that I would suggest is that you post any problems related to neptune on our community forum https://community.neptune.ml/

A lot of questions are already answered there and if not someone will know how to help you.

**Comment by rrdssfgcs** [comment]
Thanks. Maybe it's the power of gfw...

**Comment by jakubczakon** [comment]
I think it might have been connected to the release of version 2.7.1 this morning.
Please run:

`pip install neptune-cli --upgrade`

and try again.
Also we updated the gensim to newest version in this repo and loading of word2vec models would crash if you have older master so pull the latest master as well.

**Comment by rrdssfgcs** [comment]
It works~
