### ISSUE TITLE
Bugs and errors I ran into during experiment 

### ISSUE THREAD

**Issue by binglixyz** [neptune-ml/kaggle-toxic-starter#34]
Found bugs:
1. missing "," in the end of line 28 in file "pipeline_config.py".
2. missing "import nltk" in file "/steps/preprocessing.py".

Error:
1. FileNotFoundError
30.2639 | /usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
30.26557 | from ._conv import register_converters as _register_converters
30.417965 | Using TensorFlow backend.
35.018845 | Traceback (most recent call last):
35.019116 | File "/usr/local/lib/python3.6/dist-packages/deepsense/neptune/job_wrapper.py", line 113, in <module>
35.019273 | execute()
35.019429 | File "/usr/local/lib/python3.6/dist-packages/deepsense/neptune/job_wrapper.py", line 109, in execute
35.019568 | execfile(job_filepath, job_globals)
35.019697 | File "/usr/local/lib/python3.6/dist-packages/past/builtins/misc.py", line 82, in execfile
35.019829 | exec_(code, myglobals, mylocals)
35.019959 | File "main.py", line 12, in <module>
35.020092 | from pipelines import PIPELINES
35.020226 | File "/neptune/pipelines.py", line 8, in <module>
35.020365 | from steps.preprocessing import XYSplit, TextCleaner, TfidfVectorizer, WordListFilter, Normalizer, TextCounter, \
35.020523 | File "/neptune/steps/preprocessing.py", line 24, in <module>
35.020654 | with open('../external_data/apostrophes.json', 'r') as f:
35.020784 | FileNotFoundError: [Errno 2] No such file or directory: '../external_data/apostrophes.json'

 **After I copy the data from that file into the code as following, another error pops up.**
\#with open('../external_data/apostrophes.json', 'r') as f:
\#    APPO = json.load(f)
APPO = {
  "arent": "are not",
        ...,
  "well":  "will"
}

**2.  TypeError**
645.742938	Traceback (most recent call last):
645.743234	File "/usr/local/lib/python3.6/dist-packages/deepsense/neptune/job_wrapper.py", line 113, in <module>
645.743377	execute()
645.74352	File "/usr/local/lib/python3.6/dist-packages/deepsense/neptune/job_wrapper.py", line 109, in execute
645.743696	execfile(job_filepath, job_globals)
645.743897	File "/usr/local/lib/python3.6/dist-packages/past/builtins/misc.py", line 82, in execfile
645.744034	exec_(code, myglobals, mylocals)
645.744164	File "main.py", line 382, in <module>
645.744294	action()
645.744436	File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
645.744561	return self.main(*args, **kwargs)
645.744717	File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
645.744849	rv = self.invoke(ctx)
645.744996	File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
645.745155	return _process_result(sub_ctx.command.invoke(sub_ctx))
645.745335	File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
645.745471	return ctx.invoke(self.callback, **ctx.params)
645.745602	File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
645.745742	return callback(*args, **kwargs)
645.745871	File "main.py", line 129, in train_evaluate_predict_pipeline
645.746002	_train_pipeline(pipeline_name)
645.746266	File "main.py", line 68, in _train_pipeline
645.746432	_ = pipeline.fit_transform(data)
645.746566	File "/neptune/steps/base.py", line 71, in fit_transform
645.746704	step_inputs[input_step.name] = input_step.fit_transform(data)
645.746835	File "/neptune/steps/base.py", line 77, in fit_transform
645.746964	step_output_data = self._cached_fit_transform(step_inputs)
645.747093	File "/neptune/steps/base.py", line 91, in _cached_fit_transform
645.747223	step_output_data = self.transformer.fit_transform(**step_inputs)
645.747351	File "/neptune/steps/base.py", line 213, in fit_transform
645.747482	self.fit(*args, **kwargs)
645.747618	File "/neptune/models.py", line 54, in fit
645.747749	self.callbacks = self._create_callbacks(**self.callbacks_config)
645.747895	File "/neptune/models.py", line 30, in _create_callbacks
645.748021	neptune = NeptuneMonitor(**kwargs['neptune_monitor'])
645.748166	File "/neptune/steps/keras/callbacks.py", line 11, in __init__
645.748296	self.batch_loss_channel_name = get_correct_channel_name(self.ctx, 'Batch Log-loss training')
645.748426	File "/neptune/steps/keras/callbacks.py", line 38, in get_correct_channel_name
645.748554	channels_with_name = [channel for channel in ctx.job._channels if name in channel.name]
645.74869	File "/usr/local/lib/python3.6/dist-packages/deepsense/neptune/client_library/context_factory.py", line 91, in job
645.748819	, JobPropertyDeprecationWarning)
645.748948	File "/usr/local/lib/python3.6/dist-packages/deepsense/neptune/common/utils/neptune_warnings.py", line 52, in neptune_warn
645.749108	warnings.warn(message, warning_type)
645.749242	File "/usr/lib/python3.6/warnings.py", line 101, in _showwarnmsg
645.749421	_showwarnmsg_impl(msg)
645.749568	File "/usr/lib/python3.6/warnings.py", line 28, in _showwarnmsg_impl
645.749706	text = _formatwarnmsg(msg)
645.749838	File "/usr/lib/python3.6/warnings.py", line 116, in _formatwarnmsg
645.749987	msg.filename, msg.lineno, line=msg.line)
645.75013	TypeError: custom_formatwarning() got an unexpected keyword argument 'line'

How should I get it running successfully? I am running on Neptune using command "neptune send --environment keras-2.0-gpu-py3 --worker gcp-gpu-medium -- train_evaluate_predict_pipeline --pipeline_name glove_lstm". I've tried other pipeline, all fail :(

**Comment by jakubczakon** [comment]
@binglixyz 
Thank you for spotting the bugs. It should all work now.
The problem was that the path to apostrophes.json was defined relatively to steps/postprocessing and not to the main.py from which it was called. Anyhow it should work now

**Comment by binglixyz** [comment]
Thanks for your feedback! The bugs are fixed, but the last "TypeError" still exists and the error content is the same as before. Could you help with that?

**Comment by jakubczakon** [comment]
@binglixyz there was a minor problem that wasn't visible when I ran locally with `neptune run`
The difference is that when you want to access `_channels` attribute of the neptune context you should do that via 

`ctx._experiment._channels` and not `ctx.job._channels` as is going to be depraceted.

**Comment by binglixyz** [comment]
@jakubczakon Thank you very much! And thank you for explaining, it's running on Neptune now :)
