### ISSUE TITLE
is there still public/toxic_comments directory?

### ISSUE THREAD

**Issue by Morphling89** [neptune-ml/kaggle-toxic-starter#35]
Hi, I ran the experimental script and error shows that cannot find the /public/toxic_comments/single_model_predictions_20180226, so is this still there?

**Comment by jakubczakon** [comment]
I am sorry for that. I forgot to change the old single_model_predictions dir to the new one.
I have changed all the paths to the correct 
`/public/toxic_comments/single_model_predictions_03092018` and it should work just fine now.
