### ISSUE TITLE
ModuleNotFoundError: No module named 'seaborn'

### ISSUE THREAD

**Issue by cahya-wirawan** [neptune-ml/kaggle-toxic-starter#37]
Hi,

I tried the notebook neptune_ensembling.ipynb on neptune, but I got this error message:
...
ModuleNotFoundError: No module named 'seaborn'

I am not sure which combination of worker type, Python version and leading library I should use where this seaborn module is installed. Thanks.

**Comment by jakubczakon** [comment]
oh yeah simply add cell and type
`! pip install seaborn`

I will fix the notebook also

**Comment by cahya-wirawan** [comment]
Thanks for the info, I just though that all necessary modules are already installed, and the notebook is ready to be used without any additional installation
