### ISSUE TITLE
Is it possible to have access to the OOF files?

### ISSUE THREAD

**Issue by JoaoLages** [neptune-ml/kaggle-toxic-starter#40]

**Comment by jakubczakon** [comment]
@JoaoLages 
Sure you can either get them from neptune directly available in:

`/output/your_experiment_name` 

`/public/toxic_comments/single_model_predictions_03092018`

or you can get them from this public kaggle kernel https://www.kaggle.com/jakubczakon/out-of-fold-predictions-for-stacking

**Comment by kamil-kaczmarek** [comment]
@JoaoLages I think that @jakubczakon covered your question. Closing this ;-)

Best,
KK
