### ISSUE TITLE
old test data

### ISSUE THREAD

**Issue by karimiabdullah** [neptune-ml/kaggle-toxic-starter#6]
The test data in /public folder is old and so the submission output is generated for old test data. The test data for this competition has been recently changed.

**Comment by kamil-kaczmarek** [comment]
Hi @karimiabdullah,

Thanks for letting us know -> we are aware of that, so we will upload correct dataset soon. (@jakubczakon )

Best,
Kamil

**Comment by jakubczakon** [comment]
It is all updated now. Single model predictions are also updated and working fine.
